"""
DCAT-AP - Version 3.0.1

DCAT Application Profile for data portals in Europe

This module provides Pydantic-based models for the DCAT-AP 3.0.1 specification,
which extends DCAT 3 with European-specific requirements and controlled vocabularies.

DCAT-AP provides a minimal common basis within Europe to share Datasets and Data Services
cross-border and cross-domain.

References:
- https://semiceu.github.io/DCAT-AP/releases/3.0.1/
- https://www.w3.org/TR/vocab-dcat-3/

"""

# mypy: disable-error-code=misc

from __future__ import annotations

from typing import Annotated

from pydantic import Field
from rdflib import Namespace, URIRef

from dartfx.rdf.pydantic import RdfBaseModel, RdfProperty, dcterms

# Import core DCAT classes
from .dcat import (
    DCAT,
)
from .dcat import (
    Catalog as DcatCatalog,
)
from .dcat import (
    CatalogRecord as DcatCatalogRecord,
)
from .dcat import (
    DataService as DcatDataService,
)
from .dcat import (
    Dataset as DcatDataset,
)
from .dcat import (
    DatasetSeries as DcatDatasetSeries,
)
from .dcat import (
    Distribution as DcatDistribution,
)

# DCAT-AP Namespace
DCATAP = Namespace("http://data.europa.eu/r5r/")

# Additional namespaces used in DCAT-AP
ADMS = Namespace("http://www.w3.org/ns/adms#")
LOCN = Namespace("http://www.w3.org/ns/locn#")
VCARD = Namespace("http://www.w3.org/2006/vcard/ns#")
FOAF = Namespace("http://xmlns.com/foaf/0.1/")
PROV = Namespace("http://www.w3.org/ns/prov#")
SKOS = Namespace("http://www.w3.org/2004/02/skos/core#")
ODRL = Namespace("http://www.w3.org/ns/odrl/2/")
SPDX = Namespace("http://spdx.org/rdf/terms#")

# EU Vocabularies (controlled vocabularies)
EU_FREQ = Namespace("http://publications.europa.eu/resource/authority/frequency/")
EU_FILE_TYPE = Namespace("http://publications.europa.eu/resource/authority/file-type/")
EU_LANG = Namespace("http://publications.europa.eu/resource/authority/language/")
EU_THEME = Namespace("http://publications.europa.eu/resource/authority/data-theme/")
EU_ACCESS_RIGHT = Namespace("http://publications.europa.eu/resource/authority/access-right/")
EU_DIST_STATUS = Namespace("http://publications.europa.eu/resource/authority/distribution-status/")
EU_AVAILABILITY = Namespace("http://publications.europa.eu/resource/authority/planned-availability/")


class DcatAPResource(RdfBaseModel):
    """Base class for all DCAT-AP resources."""

    rdf_namespace = DCAT
    rdf_prefixes = {
        "dcat": DCAT,
        "dcatap": DCATAP,
        "dcterms": dcterms.DCTERMS,
        "adms": ADMS,
        "locn": LOCN,
        "vcard": VCARD,
        "foaf": FOAF,
        "prov": PROV,
        "skos": SKOS,
        "odrl": ODRL,
        "spdx": SPDX,
    }


# Extend core DCAT classes with DCAT-AP specific properties


class Catalog(DcatCatalog):
    """DCAT-AP Catalog.

    Extends the core DCAT Catalog with DCAT-AP specific properties.

    DCAT-AP adds:
    - Applicable legislation (mandatory for HVD)
    - Geographical coverage
    - Temporal coverage

    References:
    - https://semiceu.github.io/DCAT-AP/releases/3.0.1/#Catalogue

    """

    # DCAT-AP specific properties
    applicableLegislation: Annotated[list[str | URIRef], RdfProperty(DCATAP.applicableLegislation)] = Field(
        default_factory=list
    )
    spatial: Annotated[list[str | URIRef], RdfProperty(dcterms.DCTERMS.spatial)] = Field(default_factory=list)
    temporal: Annotated[list[str | URIRef], RdfProperty(dcterms.DCTERMS.temporal)] = Field(default_factory=list)

    def add_applicable_legislation(self, value: str | URIRef) -> str | URIRef:
        """Add applicable legislation (e.g., HVD regulation)."""
        self.applicableLegislation.append(value)
        return value

    def add_geographical_coverage(self, value: str | URIRef) -> str | URIRef:
        """Add geographical coverage (spatial)."""
        self.spatial.append(value)
        return value

    def add_temporal_coverage(self, value: str | URIRef) -> str | URIRef:
        """Add temporal coverage."""
        self.temporal.append(value)
        return value


class Dataset(DcatDataset):
    """DCAT-AP Dataset.

    Extends the core DCAT Dataset with DCAT-AP specific properties.

    DCAT-AP adds:
    - Applicable legislation (mandatory for HVD)
    - Access rights (recommended)
    - Provenance
    - Qualified attribution
    - Qualified relation
    - Was generated by
    - Other identifier

    References:
    - https://semiceu.github.io/DCAT-AP/releases/3.0.1/#Dataset

    """

    # DCAT-AP specific properties
    applicableLegislation: Annotated[list[str | URIRef], RdfProperty(DCATAP.applicableLegislation)] = Field(
        default_factory=list
    )
    accessRights: Annotated[str | URIRef | None, RdfProperty(dcterms.DCTERMS.accessRights)] = None  # type: ignore[assignment]
    provenance: Annotated[list[str | URIRef], RdfProperty(dcterms.DCTERMS.provenance)] = Field(default_factory=list)
    qualifiedAttribution: Annotated[list[str | URIRef], RdfProperty(PROV.qualifiedAttribution)] = Field(
        default_factory=list
    )
    qualifiedRelation: Annotated[list[str | URIRef], RdfProperty(DCAT.qualifiedRelation)] = Field(default_factory=list)
    wasGeneratedBy: Annotated[list[str | URIRef], RdfProperty(PROV.wasGeneratedBy)] = Field(default_factory=list)
    otherIdentifier: Annotated[list[str | URIRef], RdfProperty(ADMS.identifier)] = Field(default_factory=list)
    sample: Annotated[list[str | URIRef], RdfProperty(ADMS.sample)] = Field(default_factory=list)
    source: Annotated[list[str | URIRef], RdfProperty(dcterms.DCTERMS.source)] = Field(default_factory=list)

    def add_applicable_legislation(self, value: str | URIRef) -> str | URIRef:
        """Add applicable legislation (e.g., HVD regulation)."""
        self.applicableLegislation.append(value)
        return value

    def set_access_rights(self, value: str | URIRef) -> str | URIRef:
        """Set access rights (recommended to use EU controlled vocabulary)."""
        self.accessRights = value
        return value

    def add_provenance(self, value: str | URIRef) -> str | URIRef:
        """Add provenance statement."""
        self.provenance.append(value)
        return value

    def add_qualified_attribution(self, value: str | URIRef) -> str | URIRef:
        """Add qualified attribution."""
        self.qualifiedAttribution.append(value)
        return value

    def add_qualified_relation(self, value: str | URIRef) -> str | URIRef:
        """Add qualified relation."""
        self.qualifiedRelation.append(value)
        return value

    def add_was_generated_by(self, value: str | URIRef) -> str | URIRef:
        """Add activity that generated this dataset."""
        self.wasGeneratedBy.append(value)
        return value

    def add_other_identifier(self, value: str | URIRef) -> str | URIRef:
        """Add other identifier (ADMS identifier)."""
        self.otherIdentifier.append(value)
        return value

    def add_sample(self, value: str | URIRef) -> str | URIRef:
        """Add sample distribution."""
        self.sample.append(value)
        return value

    def add_source(self, value: str | URIRef) -> str | URIRef:
        """Add source dataset."""
        self.source.append(value)
        return value


class Distribution(DcatDistribution):
    """DCAT-AP Distribution.

    Extends the core DCAT Distribution with DCAT-AP specific properties.

    DCAT-AP adds:
    - Applicable legislation (mandatory for HVD)
    - Availability (planned availability)
    - Has policy (ODRL policy)
    - Linked schemas
    - Status (distribution status)

    References:
    - https://semiceu.github.io/DCAT-AP/releases/3.0.1/#Distribution

    """

    # DCAT-AP specific properties
    applicableLegislation: Annotated[list[str | URIRef], RdfProperty(DCATAP.applicableLegislation)] = Field(
        default_factory=list
    )
    availability: Annotated[str | URIRef | None, RdfProperty(DCATAP.availability)] = None
    hasPolicy: Annotated[list[str | URIRef], RdfProperty(ODRL.hasPolicy)] = Field(default_factory=list)
    linkedSchemas: Annotated[list[str | URIRef], RdfProperty(dcterms.DCTERMS.conformsTo)] = Field(default_factory=list)
    status: Annotated[str | URIRef | None, RdfProperty(ADMS.status)] = None

    def add_applicable_legislation(self, value: str | URIRef) -> str | URIRef:
        """Add applicable legislation (e.g., HVD regulation)."""
        self.applicableLegislation.append(value)
        return value

    def set_availability(self, value: str | URIRef) -> str | URIRef:
        """Set planned availability (use EU controlled vocabulary)."""
        self.availability = value
        return value

    def add_policy(self, value: str | URIRef) -> str | URIRef:
        """Add ODRL policy."""
        self.hasPolicy.append(value)
        return value

    def add_linked_schema(self, value: str | URIRef) -> str | URIRef:
        """Add linked schema."""
        self.linkedSchemas.append(value)
        return value

    def set_status(self, value: str | URIRef) -> str | URIRef:
        """Set distribution status (use EU controlled vocabulary)."""
        self.status = value
        return value


class DataService(DcatDataService):
    """DCAT-AP Data Service.

    Extends the core DCAT DataService with DCAT-AP specific properties.

    DCAT-AP adds:
    - Applicable legislation (mandatory for HVD)

    References:
    - https://semiceu.github.io/DCAT-AP/releases/3.0.1/#DataService

    """

    # DCAT-AP specific properties
    applicableLegislation: Annotated[list[str | URIRef], RdfProperty(DCATAP.applicableLegislation)] = Field(
        default_factory=list
    )

    def add_applicable_legislation(self, value: str | URIRef) -> str | URIRef:
        """Add applicable legislation (e.g., HVD regulation)."""
        self.applicableLegislation.append(value)
        return value


class DatasetSeries(DcatDatasetSeries):
    """DCAT-AP Dataset Series.

    Extends the core DCAT DatasetSeries with DCAT-AP specific properties.

    DCAT-AP adds:
    - Applicable legislation (mandatory for HVD)
    - Access rights

    References:
    - https://semiceu.github.io/DCAT-AP/releases/3.0.1/#DatasetSeries

    """

    # DCAT-AP specific properties
    applicableLegislation: Annotated[list[str | URIRef], RdfProperty(DCATAP.applicableLegislation)] = Field(
        default_factory=list
    )
    accessRights: Annotated[str | URIRef | None, RdfProperty(dcterms.DCTERMS.accessRights)] = None  # type: ignore[assignment]

    def add_applicable_legislation(self, value: str | URIRef) -> str | URIRef:
        """Add applicable legislation (e.g., HVD regulation)."""
        self.applicableLegislation.append(value)
        return value

    def set_access_rights(self, value: str | URIRef) -> str | URIRef:
        """Set access rights (recommended to use EU controlled vocabulary)."""
        self.accessRights = value
        return value


class CatalogRecord(DcatCatalogRecord):
    """DCAT-AP Catalog Record.

    Extends the core DCAT CatalogRecord with DCAT-AP specific properties.

    DCAT-AP adds:
    - Applicable legislation (mandatory for HVD)

    References:
    - https://semiceu.github.io/DCAT-AP/releases/3.0.1/#CatalogueRecord

    """

    # DCAT-AP specific properties
    applicableLegislation: Annotated[list[str | URIRef], RdfProperty(DCATAP.applicableLegislation)] = Field(
        default_factory=list
    )

    def add_applicable_legislation(self, value: str | URIRef) -> str | URIRef:
        """Add applicable legislation (e.g., HVD regulation)."""
        self.applicableLegislation.append(value)
        return value


# Rebuild models to handle forward references
Catalog.model_rebuild()
Dataset.model_rebuild()
Distribution.model_rebuild()
DataService.model_rebuild()
DatasetSeries.model_rebuild()
CatalogRecord.model_rebuild()


# Controlled Vocabulary Constants
class ControlledVocabularies:
    """DCAT-AP Controlled Vocabularies.

    These are the controlled vocabularies that MUST or SHOULD be used
    for specific properties in DCAT-AP.

    References:
    - https://semiceu.github.io/DCAT-AP/releases/3.0.1/#controlled-vocabularies

    """

    # Mandatory controlled vocabularies
    IANA_MEDIA_TYPES = "http://www.iana.org/assignments/media-types/media-types.xhtml"
    EU_FREQUENCY = "http://publications.europa.eu/resource/authority/frequency"
    EU_FILE_TYPE = "http://publications.europa.eu/resource/authority/file-type"
    EU_LANGUAGES = "http://publications.europa.eu/resource/authority/language"
    EU_DISTRIBUTION_STATUS = "http://publications.europa.eu/resource/authority/distribution-status"
    EU_AVAILABILITY = "http://publications.europa.eu/resource/authority/planned-availability"
    SPDX_CHECKSUM_ALGORITHM = "https://spdx.org/rdf/terms/#d4e2129"

    # At least 1 value from controlled vocabulary
    EU_DATA_THEME = "http://publications.europa.eu/resource/authority/data-theme"

    # Recommended controlled vocabularies
    ADMS_PUBLISHER_TYPE = "http://purl.org/adms/publishertype/1.0"
    ADMS_LICENCE_TYPE = "http://purl.org/adms/licencetype/1.0"
    EU_ACCESS_RIGHT = "http://publications.europa.eu/resource/authority/access-right"

    # Optional controlled vocabularies
    EU_CORPORATE_BODIES = "http://publications.europa.eu/resource/authority/corporate-body"
    EU_CONTINENTS = "http://publications.europa.eu/resource/authority/continent/"
    EU_COUNTRIES = "http://publications.europa.eu/resource/authority/country"
    EU_PLACES = "http://publications.europa.eu/resource/authority/place/"
    GEONAMES = "http://sws.geonames.org/"
    EU_DATASET_TYPE = "http://publications.europa.eu/resource/authority/dataset-type"


# High Value Datasets (HVD) support
class HVDCategory:
    """High Value Datasets Categories.

    The six thematic categories of High Value Datasets as defined in
    Commission Implementing Regulation (EU) 2023/138.

    References:
    - https://eur-lex.europa.eu/eli/reg_impl/2023/138/oj

    """

    GEOSPATIAL = "http://data.europa.eu/bna/c_164e0bf5"
    EARTH_OBSERVATION = "http://data.europa.eu/bna/c_a9135398"
    ENVIRONMENT = "http://data.europa.eu/bna/c_ac64a52d"
    METEOROLOGICAL = "http://data.europa.eu/bna/c_b803a9a9"
    STATISTICS = "http://data.europa.eu/bna/c_dd313021"
    COMPANIES = "http://data.europa.eu/bna/c_e1da4e07"


__all__ = [
    # Namespaces
    "DCATAP",
    "ADMS",
    "LOCN",
    "VCARD",
    "FOAF",
    "PROV",
    "SKOS",
    "ODRL",
    "SPDX",
    # Base class
    "DcatAPResource",
    # Extended DCAT classes
    "Catalog",
    "Dataset",
    "Distribution",
    "DataService",
    "DatasetSeries",
    "CatalogRecord",
    # Controlled vocabularies
    "ControlledVocabularies",
    "HVDCategory",
]
